### ISSUE TITLE
例子

### ISSUE THREAD

**Issue by wayne-lu** [besley/SlickOne#1]
有没有关于 slickone 详细一点的例子，里面很多东西都没用到。

**Comment by besley** [comment]
hi，在SlickOne.Web项目里面有基本示例，如果方便，请你列出你需要的功能示例，我们近期的下个版本会考虑增加这些功能示例。

**Comment by besley** [comment]
已经添加了新增编辑删除查询等方法示例，可以查看在线DEMO页面。
https://github.com/besley/SlickOne

**Comment by besley** [comment]
在线ＤＥＭＯ页面地址：

**Comment by besley** [comment]
在线DEMO页面地址：
http://demo.slickflow.com/soweb/
