### ISSUE TITLE
Repository的DeleteBatch方法都没transaction？

### ISSUE THREAD

**Issue by zengfanlin** [besley/SlickOne#2]
` public int DeleteBatch<T>(IDbConnection conn, IEnumerable<dynamic> ids, IDbTransaction transaction = null) where T : class
        {
            var tblName = GetTableName<T>();
            var idsin = string.Join(",", ids.ToArray<dynamic>());
            var sql = string.Format("DELETE FROM {0} WHERE ID in (@ids)", tblName);
            var result = SqlMapper.Execute(conn, sql, new { ids = idsin },transaction);

            return result;
        }`

**Comment by besley** [comment]
@zengfanlin ,Thanks , we have fixed this issue from yours code. :)
