### ISSUE TITLE
Update to bootstrap 4 or 5 beta and nugets

### ISSUE THREAD

**Issue by papyr** [besley/SlickOne#4]
Hello any updates coming

**Comment by besley** [comment]
Hi, Thanks for your requirement, we will make a plan to upgrade bootstrap5. But it will not be immediately, at this time the version is bootstrap 5 alpha2.

**Comment by besley** [comment]
If you have any commercial application, you can write to our support team: sales@ruochisoft.com, Thanks

**Comment by papyr** [comment]
trying to see if this can fit/replace something I have, in asp core application.. will let you know. 

Many of your demos dont work

**Comment by besley** [comment]
Hi, there is an online demo, we used it for our product too, it's based on the SlickOne project.
http://demo.slickflow.com/sfd/
http://demo.slickflow.com/smd2/

**Comment by papyr** [comment]
Can you please update and link to latest version BS 4.52, when we tried it was not rendering correctly.

I can refer you to my boss if the sample works, we need an Inbox concept with pending, completed, assigned by user. Perhaps consider some license or donation. But first, we need to be able to replace another workflow

**Comment by besley** [comment]
Hi, I have reported your requirement to our team, we will make a plan to upgrade the bootstrap to the latest version. If you can think about the slickflow enterprise license, it will be a better choice for the team. Thanks
